# Generated by Django 6.0.5 on 2026-05-18 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_email', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(blank=True, max_length=300)),
                ('phishing_probability', models.IntegerField(default=0)),
                ('threat_level', models.CharField(choices=[('SAFE', 'Safe'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='SAFE', max_length=20)),
                ('analysis_json', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('why_dangerous', models.TextField(blank=True)),
                ('ai_confidence', models.IntegerField(default=0)),
                ('parsed_email', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
